### ISSUE TITLE
free_instance crash the program

### ISSUE THREAD

**Issue by jywang2016** [lbl-srg/EnergyPlusToFMU#29]
I want `initialize` and `free_instance` the model again and again. In this process, I try to set value for the concerned variable until I can find the appropriate value of it. However, the `free_instance` function seems to crash the program(python). Here is an simple implementation. 
```
import pyfmi

model = pyfmi.load_fmu('../model.fmu')

t_start = 60*60*24*195
t_step_size = 15 * 60
t_end = 60*60*24*227

model.instantiate_slave()

for j in range(10):
    model.initialize(t_start,t_end,True)

    for i in range(10):
        print('i',i,' Qin: ',model.get('Qin'),'\n')
        model.set('Q',i+1)
        t = t_start + i*t_step_size
        model.do_step(t,t_step_size,new_step = True)
    print('j:',j,'over!\n')
    model.free_instance()
```
Is there any way to free the process of Energyplus without crashing the program.

Thanks

JY

**Comment by tsnouidui** [comment]
There are few issues here:
 First: My recollection of PyFMI is that  `load_fmu()` instantiates the FMU so you don't need to call `model.instantiate_slave()`. 
Second: even if you were to free the instance, you wouldn't be able to use/initialize the same FMU multiple times because of some processes being locked by the EnergyPlus engine. 

A workaround may be to do something along the lines below. Please note that I have slightly modified the code to get the variable which is in my FMU. I don't know whether you could use this approach for your specific need though.

```
for j in range(3):
    name="model"+str(j)
    name=load_fmu(fmu=fmu_path)
    name.initialize(t_start,t_end,True)
    for i in range(10):
        print('i',i,' TRooMea: ',name.get('TRooMea'),'\n')
        #name.set('Q',i+1)
        t = t_start + i*t_step_size
        name.do_step(t,t_step_size,new_step = True)
```

**Comment by jywang2016** [comment]
Thanks for your help! It works for me.
